stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "some tests should be done..."

# Building with Docker in Docker
build:
  stage: build
  image: docker:stable
  services:
    - docker:19-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker image build -f Dockerfile -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF .
    - docker image push $CI_REGISTRY_IMAGE:latest
    - docker image push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  only:
    - master
